from SaitamaRobot import (DEV_USERS, WORLD_GOVT, ADMIRALS, WARLORDS, REVOLUTIONARIES, telethn)

IMMUNE_USERS = WORLD_GOVT + REVOLUTIONARIES + ADMIRALS + WARLORDS + DEV_USERS

IMMUNE_USERS = list(WORLD_GOVT) + list(REVOLUTIONARIES) + list(ADMIRALS) + list(
    WARLORDS) + list(DEV_USERS)
